name: trumptastic
dependencies:
- cycler=0.10.0=py35_0
- freetype=2.5.5=1
- libpng=1.6.22=0
- matplotlib=1.5.1=np111py35_0
- mkl=11.3.3=0
- nltk=3.2.1=py35_0
- numpy=1.11.1=py35_0
- openssl=1.0.2h
- pip=8.1.2=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- qt=4.8.7=4
- readline=6.2=2
- scikit-learn=0.17.1=np111py35_2
- scipy=0.18.0=np111py35_0
- setuptools=25.1.6=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - click==6.6
  - dominate==2.2.1
  - flask==0.11.1
  - flask-bootstrap==3.3.6.0
  - flask-wtf==0.12
  - itsdangerous==0.24
  - jinja2==2.8
  - keras==1.0.7
  - markupsafe==0.23
  - pyyaml==3.11
  - git+https://github.com/pyinstaller/pyinstaller.git#egg=pyinstaller
  - visitor==0.1.3
  - werkzeug==0.11.10
  - wtforms==2.1
